/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagenda.view;

import com.mycompany.sistemaagenda.model.Event;
import com.mycompany.sistemaagenda.model.User;
import java.util.ArrayList;

/**
 *
 * @author pedrh
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    
    ArrayList<User> users;
    ArrayList<Event> events;
    
    public Admin() {
        initComponents();
        users = loadUsers();
        events = loadEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEventBt = new javax.swing.JButton();
        deleteUserBr = new javax.swing.JButton();
        editEventBt = new javax.swing.JButton();
        userTb = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eventTb = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        loadParticipantsBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setPreferredSize(new java.awt.Dimension(700, 423));

        addEventBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addEventBt.setText("Adicionar Evento");
        addEventBt.setMaximumSize(new java.awt.Dimension(107, 29));
        addEventBt.setMinimumSize(new java.awt.Dimension(107, 29));
        addEventBt.setPreferredSize(new java.awt.Dimension(161, 49));
        addEventBt.addActionListener(this::addEventBtActionPerformed);

        deleteUserBr.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deleteUserBr.setText("Excluir Usuário");
        deleteUserBr.addActionListener(this::deleteUserBrActionPerformed);

        editEventBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editEventBt.setText("Editar Evento");
        editEventBt.addActionListener(this::editEventBtActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuários"
            }
        ));
        userTb.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Eventos"
            }
        ));
        eventTb.setViewportView(jTable2);

        loadParticipantsBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loadParticipantsBt.setText("Ver Participantes");
        loadParticipantsBt.addActionListener(this::loadParticipantsBtActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEventBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUserBr)
                    .addComponent(loadParticipantsBt)
                    .addComponent(editEventBt))
                .addGap(18, 18, 18)
                .addComponent(eventTb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userTb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addEventBt, deleteUserBr, editEventBt, loadParticipantsBt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addEventBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editEventBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadParticipantsBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteUserBr)))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addEventBt, deleteUserBr, editEventBt, loadParticipantsBt});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEventBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventBtActionPerformed
        addEvent();
    }//GEN-LAST:event_addEventBtActionPerformed

    private void deleteUserBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBrActionPerformed
        deleteUser();
    }//GEN-LAST:event_deleteUserBrActionPerformed

    private void loadParticipantsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadParticipantsBtActionPerformed
        loadParticipants();
    }//GEN-LAST:event_loadParticipantsBtActionPerformed

    private void editEventBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventBtActionPerformed
        editEvent();
    }//GEN-LAST:event_editEventBtActionPerformed

    private void addEvent(){
        
    }
    private void editEvent(){
        
    }
    private void deleteUser(){
        
    }
    private void loadParticipants(){
        
    }
    private ArrayList<User> loadUsers(){
        ArrayList<User> users = new ArrayList();        
        return users;
    }
    private ArrayList<Event> loadEvents(){
        ArrayList<Event> events = new ArrayList();        
        return events;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEventBt;
    private javax.swing.JButton deleteUserBr;
    private javax.swing.JButton editEventBt;
    private javax.swing.JScrollPane eventTb;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loadParticipantsBt;
    private javax.swing.JScrollPane userTb;
    // End of variables declaration//GEN-END:variables
}
