/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagenda.view;

import com.mycompany.sistemaagenda.controller.CommonUserController;
import javax.swing.JOptionPane;


public class CommonUser extends javax.swing.JFrame {
    private CommonUserController ctrl;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CommonUser.class.getName());

    /**
     * Creates new form User
     */
    public CommonUser() {
        initComponents();
    }
    
    public void setController(CommonUserController ctrl){
        this.ctrl = ctrl;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventosDisponiveis_botao = new javax.swing.JButton();
        eventosCadastrados_botao = new javax.swing.JButton();
        sair_botao = new javax.swing.JButton();
        ola_texto = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        opcoes_menu = new javax.swing.JMenu();
        eventosDisponiveis_menuItem = new javax.swing.JMenuItem();
        eventosCadastrados_menuItem = new javax.swing.JMenuItem();
        sair_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventosDisponiveis_botao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventosDisponiveis_botao.setText("Eventos Disponíveis");
        eventosDisponiveis_botao.addActionListener(this::eventosDisponiveis_botaoActionPerformed);

        eventosCadastrados_botao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventosCadastrados_botao.setText("Eventos Cadastrados");
        eventosCadastrados_botao.addActionListener(this::eventosCadastrados_botaoActionPerformed);

        sair_botao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sair_botao.setText("Sair");
        sair_botao.addActionListener(this::sair_botaoActionPerformed);

        ola_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ola_texto.setText("Olá,");

        opcoes_menu.setText("Opções");

        eventosDisponiveis_menuItem.setText("Eventos Disponíveis");
        eventosDisponiveis_menuItem.addActionListener(this::eventosDisponiveis_menuItemActionPerformed);
        opcoes_menu.add(eventosDisponiveis_menuItem);

        eventosCadastrados_menuItem.setText("Eventos Cadastrados");
        eventosCadastrados_menuItem.addActionListener(this::eventosCadastrados_menuItemActionPerformed);
        opcoes_menu.add(eventosCadastrados_menuItem);

        sair_menuItem.setText("Sair");
        sair_menuItem.addActionListener(this::sair_menuItemActionPerformed);
        opcoes_menu.add(sair_menuItem);

        barraMenu.add(opcoes_menu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sair_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eventosCadastrados_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eventosDisponiveis_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ola_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ola_texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eventosDisponiveis_botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventosCadastrados_botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sair_botao)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sair_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_menuItemActionPerformed
        ctrl.sair();
    }//GEN-LAST:event_sair_menuItemActionPerformed

    private void eventosDisponiveis_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosDisponiveis_botaoActionPerformed
        EventosDisponiveis eventosDisponiveis = new EventosDisponiveis();
        //eventosDisponiveis.preencherTabela(); -> ainda em andamento
        eventosDisponiveis.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosDisponiveis_botaoActionPerformed

    private void eventosCadastrados_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosCadastrados_botaoActionPerformed
        EventosCadastrados eventosCadastrados = new EventosCadastrados();
        //eventosCadastrados.preencherTabela(); -> ainda em andamento
        eventosCadastrados.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosCadastrados_botaoActionPerformed

    private void sair_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_botaoActionPerformed
        ctrl.sair();
    }//GEN-LAST:event_sair_botaoActionPerformed

    private void eventosDisponiveis_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosDisponiveis_menuItemActionPerformed
        EventosDisponiveis eventosDisponiveis = new EventosDisponiveis();
        //eventosDisponiveis.preencherTabela(); -> ainda em andamento
        eventosDisponiveis.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosDisponiveis_menuItemActionPerformed

    private void eventosCadastrados_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosCadastrados_menuItemActionPerformed
        EventosCadastrados eventosCadastrados = new EventosCadastrados();
        //eventosCadastrados.preencherTabela(); -> ainda em andamento
        eventosCadastrados.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosCadastrados_menuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CommonUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton eventosCadastrados_botao;
    private javax.swing.JMenuItem eventosCadastrados_menuItem;
    private javax.swing.JButton eventosDisponiveis_botao;
    private javax.swing.JMenuItem eventosDisponiveis_menuItem;
    private javax.swing.JLabel ola_texto;
    private javax.swing.JMenu opcoes_menu;
    private javax.swing.JButton sair_botao;
    private javax.swing.JMenuItem sair_menuItem;
    // End of variables declaration//GEN-END:variables
}
