/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagenda.view;

import com.mycompany.sistemaagenda.dao.EventDAO;
import com.mycompany.sistemaagenda.model.Event;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrh
 */
public class EditEventDialog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditEventDialog.class.getName());

    /**
     * Creates new form EditEventDialog
     */
    public EditEventDialog() {
        initComponents();
    }
    
    private Event event = new Event();
    private Admin admin = new Admin();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    
    public EditEventDialog(Admin admin, Event event){
        this.event = event;
        this.admin = admin;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventDateLabel = new javax.swing.JLabel();
        eventDateFtf = new javax.swing.JFormattedTextField();
        eventSpeakerLabel = new javax.swing.JLabel();
        eventNameTf = new javax.swing.JTextField();
        eventNameLabel = new javax.swing.JLabel();
        eventSpeakerTf = new javax.swing.JTextField();
        eventRoomLabel = new javax.swing.JLabel();
        eventRoomTf = new javax.swing.JTextField();
        saveEditBt = new javax.swing.JButton();
        cancelEditBt = new javax.swing.JButton();
        eventFeeLabel = new javax.swing.JLabel();
        eventFeeTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Evento");
        setPreferredSize(new java.awt.Dimension(400, 425));

        eventDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eventDateLabel.setText("Data e hora");

        try {
            eventDateFtf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        eventSpeakerLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eventSpeakerLabel.setText("Palestrante");

        eventNameTf.setPreferredSize(new java.awt.Dimension(64, 26));
        eventNameTf.addActionListener(this::eventNameTfActionPerformed);

        eventNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eventNameLabel.setText("Nome");

        eventSpeakerTf.setPreferredSize(new java.awt.Dimension(64, 26));

        eventRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eventRoomLabel.setText("Sala");

        eventRoomTf.setPreferredSize(new java.awt.Dimension(64, 26));

        saveEditBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveEditBt.setText("Salvar");
        saveEditBt.addActionListener(this::saveEditBtActionPerformed);
        saveEditBt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveEditBtKeyPressed(evt);
            }
        });

        cancelEditBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cancelEditBt.setText("Cancelar");
        cancelEditBt.addActionListener(this::cancelEditBtActionPerformed);
        cancelEditBt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelEditBtKeyPressed(evt);
            }
        });

        eventFeeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eventFeeLabel.setText("Inscrição");

        eventFeeTf.setPreferredSize(new java.awt.Dimension(64, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelEditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveEditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eventSpeakerTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eventRoomTf, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 31, Short.MAX_VALUE))
                                    .addComponent(eventRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eventFeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eventDateFtf)
                                    .addComponent(eventDateLabel)))
                            .addComponent(eventFeeTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eventSpeakerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(eventNameTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(eventNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventSpeakerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventSpeakerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(eventRoomTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventDateLabel)
                            .addComponent(eventRoomLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventDateFtf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventFeeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eventFeeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveEditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelEditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveEditBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditBtActionPerformed
        saveEdit();
    }//GEN-LAST:event_saveEditBtActionPerformed

    private void saveEditBtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveEditBtKeyPressed
        saveEdit();
    }//GEN-LAST:event_saveEditBtKeyPressed

    private void cancelEditBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditBtActionPerformed
        dispose();
    }//GEN-LAST:event_cancelEditBtActionPerformed

    private void cancelEditBtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelEditBtKeyPressed
        dispose();
    }//GEN-LAST:event_cancelEditBtKeyPressed

    private void eventNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameTfActionPerformed

    public void loadData(){
        eventNameTf.setText(event.getName());
        eventSpeakerTf.setText(event.getSpeaker());
        eventRoomTf.setText(Integer.toString(event.getRoom()));
        eventFeeTf.setText(Integer.toString(event.getFee()));
        eventDateFtf.setText(event.getDate().format(formatter));
    }
    
    public void saveEdit(){
        String name = eventNameTf.getText();
        String speaker = eventSpeakerTf.getText();
        String roomText = eventRoomTf.getText().trim();
        String feeText = eventFeeTf.getText().trim();
        int room;
        int fee;
        try{
            room = Integer.parseInt(roomText);
            fee = Integer.parseInt(feeText);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Os campos Sala e Inscrição devem ser valores numéricos.");
            return;
        }
        if(name.isEmpty() || speaker.isEmpty() || roomText.isEmpty() || feeText.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum dos campos podem ser vazios.");
            return;
        }        
        LocalDateTime date = LocalDateTime.parse(eventDateFtf.getText(), formatter);
        Event updtEvent = new Event(date, room, name, speaker, fee);
        EventDAO eventDAO = new EventDAO();
        try{
            eventDAO.updateEvent(this.event, updtEvent);
            admin.events = admin.loadEvents();
            admin.loadEventsOnTable();
            dispose();
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao editar os valores");
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditEventDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelEditBt;
    private javax.swing.JFormattedTextField eventDateFtf;
    private javax.swing.JLabel eventDateLabel;
    private javax.swing.JLabel eventFeeLabel;
    private javax.swing.JTextField eventFeeTf;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JTextField eventNameTf;
    private javax.swing.JLabel eventRoomLabel;
    private javax.swing.JTextField eventRoomTf;
    private javax.swing.JLabel eventSpeakerLabel;
    private javax.swing.JTextField eventSpeakerTf;
    private javax.swing.JButton saveEditBt;
    // End of variables declaration//GEN-END:variables
}
